# -*- coding: utf-8 -*-
"""data_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137r-ayp7ggxYdu_-59C9krRwEUgQ20ac

Required Libraries
"""

import joblib
import numpy as np
import pandas as pd

"""Loads all previously created objects used for data preprocessing."""

transformer_Age_at_enrollment = joblib.load("students_performance/model/transformer_Age_at_enrollment.joblib")
transformer_Curricular_units_1st_sem_grade = joblib.load("students_performance/model/transformer_Curricular_units_1st_sem_grade.joblib")
transformer_Curricular_units_2nd_sem_grade = joblib.load("students_performance/model/transformer_Curricular_units_2nd_sem_grade.joblib")
transformer_Debtor = joblib.load("students_performance/model/transformer_Debtor.joblib")
transformer_Displaced = joblib.load("students_performance/model/transformer_Displaced.joblib")
transformer_Educational_special_needs = joblib.load("students_performance/model/transformer_Educational_special_needs.joblib")
transformer_GDP = joblib.load("students_performance/model/transformer_GDP.joblib")
transformer_Gender = joblib.load("students_performance/model/transformer_Gender.joblib")
transformer_Scholarship_holder = joblib.load("students_performance/model/transformer_Scholarship_holder.joblib")
transformer_Tuition_fees_up_to_date = joblib.load("students_performance/model/transformer_Tuition_fees_up_to_date.joblib")
transformer_Unemployment_rate = joblib.load("students_performance/model/transformer_Unemployment_rate.joblib")

def data_preprocessing(data):
  data = data.copy()
  df = pd.DataFrame()
  
  df["transformer_Age_at_enrollment"] = transformer_Age_at_enrollment.transform(np.asarray(data["transformer_Age_at_enrollment"]).reshape(-1, 1))[0]
    
  df["transformer_Curricular_units_1st_sem_grade"] = transformer_Curricular_units_1st_sem_grade.transform(np.asarray(data["transformer_Curricular_units_1st_sem_grade"]).reshape(-1, 1))[0]
    
  df["transformer_Curricular_units_2nd_sem_grade"] = transformer_Curricular_units_2nd_sem_grade.transform(np.asarray(data["transformer_Curricular_units_2nd_sem_grade"]).reshape(-1, 1))[0]

  df["transformer_Unemployment_rate"] = transformer_Unemployment_rate.transform(np.asarray(data["transformer_Unemployment_rate"]).reshape(-1, 1))[0]
    
  df["transformer_GDP"] = transformer_GDP.transform(np.asarray(data["transformer_GDP"]).reshape(-1, 1))[0]

  df["transformer_Gender"] = transformer_Gender.transform(np.asarray(data["transformer_Gender"]).reshape(-1, 1))[0]

  df["transformer_Displaced"] = transformer_Displaced.transform(np.asarray(data["transformer_Displaced"]).reshape(-1, 1))[0]

  df["transformer_Educational_special_needs"] = transformer_Educational_special_needs.transform(np.asarray(data["transformer_Educational_special_needs"]).reshape(-1, 1))[0]
    
  df["transformer_Debtor"] = transformer_Debtor.transform(np.asarray(data["transformer_Debtor"]).reshape(-1, 1))[0]

  df["transformer_Tuition_fees_up_to_date"] = transformer_Tuition_fees_up_to_date.transform(np.asarray(data["transformer_Tuition_fees_up_to_date"]).reshape(-1, 1))[0]
    
  df["transformer_Scholarship_holder"] = transformer_Scholarship_holder.transform(np.asarray(data["transformer_Scholarship_holder"]).reshape(-1, 1))[0]

  return df
